apiVersion: v1
kind: Service
metadata:
  name: {{ include "trino-gw.fullname" . }}
  labels:
    {{- include "trino-gw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.requestRouter }}
      targetPort: requestRouter
      protocol: TCP
      name: requestRouter
    - port: {{ .Values.service.application }}
      targetPort: application
      protocol: TCP
      name: application-port
    - port: {{ .Values.service.admin }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "trino-gw.selectorLabels" . | nindent 4 }}
